# --- Основные настройки приложения ---
spring.application.name=portal

# --- Настройки подключения к базе данных ---
spring.datasource.url=jdbc:postgresql://localhost:5432/portal
spring.datasource.username=${DB_USERNAME:dir}
spring.datasource.password=${DB_PASSWORD:852456}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Настройки JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- Настройки Flyway (миграции выполняются автоматически при старте) ---
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://localhost:5432/portal
spring.flyway.user=${DB_USERNAME:dir}
spring.flyway.password=${DB_PASSWORD:852456}
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=public
spring.flyway.baseline-on-migrate=true

# --- Настройки JWT ---
jwt.secret=${JWT_SECRET:dev-secret-key-change-me-v7Kq9pjghjR3xN8u8Yj3LzWb4gld445hhgfdssvAAAABBBCCCDDDEEE}
jwt.expiration=86400000
jwt.refresh.expiration=2592000000


# --- Настройки Redis ---
spring.data.redis.host=localhost
spring.data.redis.port=6379

add.default.admin.password=${ADMIN_PASSWORD:_portal2412_admin0601!}