# --- Основные настройки приложения ---
spring.application.name=portal

# --- Настройки подключения к базе данных ---
spring.datasource.url=jdbc:postgresql://localhost:5432/portal
spring.datasource.username=dir
spring.datasource.password=852456
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Настройки JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# --- Настройки Flyway (миграции выполняются автоматически при старте) ---
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://localhost:5432/portal
spring.flyway.user=dir
spring.flyway.password=852456
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=public
spring.flyway.baseline-on-migrate=true

jwt.secret=v7#Kq9@pA2mR$5xN!u8Y&j3LzWb1Qc4
jwt.expiration=86400000
